#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#    url: jdbc:mysql://localhost:3306/stackoverflow
#    username: root
#    password: 7642
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
#        format_sql: true
#
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1093533041933-6g4ifvse2jvudptjhg5d2tpbefiqr9l4.apps.googleusercontent.com
            clientSecret: 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
