spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stackoverflow?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul&useSSL=true
    username: root
<<<<<<< HEAD
    password: 7642
=======
#    password: admin1234
    password: jiwon
>>>>>>> 6f1e2ab8cf39f2b4da099385b7906b611a90a27f

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:

#        show_sql: true
#        format_sql: true


server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: stackoverflow123412341234123412341234
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    p6spy: info


#
#    spring:
#      h2:
#        console:
#          enabled: true
#          path: /h2
#      datasource:
#        url: jdbc:h2:mem:test
#      jpa:
#        hibernate:
#          ddl-auto: create  # (1) 스키마 자동 생성
#        show-sql: true      # (2) SQL 쿼리 출력
#        properties:
#          hibernate:
#            format_sql: true  # (3) SQL pretty print
#      sql:
#        init:
#          data-locations: classpath*:db/h2/data.sql
#      security:
#        oauth2:
#          #      client:
#          registration:
#            google:
#              clientId: 1093533041933-6g4ifvse2jvudptjhg5d2tpbefiqr9l4.apps.googleusercontent.com
#              clientSecret: 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
#              scope:
#                - email
#                - profile
#    logging:
#      level:
#        org:
#          springframework:
#            orm:
#              jpa: DEBUG
#    server:
#      servlet:
#        encoding:
#          force-response: true
#    mail:
#      address:
#        admin: admin@gmail.com
#    jwt:
#      key:
#        secret: kevin1234123412341234123412341234
#      access-token-expiration-minutes: 30
#      refresh-token-expiration-minutes: 420