spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-seb26.cf1yjajysgdl.ap-northeast-2.rds.amazonaws.com:13306/seb26?useSSL=false&characterEncoding=UTF-8
    username: seb26
    password: "!!CodeStates45!!"

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1093533041933-6g4ifvse2jvudptjhg5d2tpbefiqr9l4.apps.googleusercontent.com
            clientSecret: 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
            scope: email,profile

  logging:
    level:
      org.springframework.orm.jpa: DEBUG

  server:
    servlet:
      encoding:
        force-response: true

  mail:
    address:
      admin: admin@gmail.com

jwt:
  key:
    secret: kevin1234123412341234123412341234
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
